use super::{Command, Block};

grammar;

pub Command: Command = {
    "test" => Command::Test,
    "place" <block:Block> => Command::Place(block),
    "render" <distance:Int> => Command::RenderDistance(distance as f32),
};

Block: Block = {
    "air" => Block::Air,
    "stone" => Block::Stone,
    "sand" => Block::Sand,
    "grass" => Block::Grass,
    "water" => Block::Water,
    "log" => Block::Log,
    "leaves" => Block::Leaves,
}

Int: i32 = <s:r"[0-9]+"> => s.parse().unwrap();
